In [1]:
import requests
from bs4 import BeautifulSoup
import pandas as pd

In [2]:
url = "https://en.wikipedia.org/wiki/World_Happiness_Report"

In [3]:
website_url = requests.get(url).text
soup = BeautifulSoup(website_url,'lxml')
table = soup.find("table",{"class":"wikitable sortable"})
body = table.find("tbody")
rows = body.findChildren(['th', 'tr'])

In [4]:
countries = []
happiness_list = []
GDP_per_capita_list = []
social_support_list = []
healthy_life_exp_list = []
freedom_list = []
generosity_list = []
corruption_list = []

In [5]:
for row in rows:
    cells = row.findChildren(['td'])
    if len(cells) > 0:
        
        country = cells[1].findAll('a')[0].text
        if country == '':
            country = cells[1].findAll('a')[1].text
        countries.append(country)
        
        happiness = cells[2].text.split('\n')[0]
        happiness_list.append(happiness)
        
        GDP_per_capita = cells[3].text.split('\n')[0]
        GDP_per_capita_list.append(GDP_per_capita)
        
        social_support = cells[4].text.split('\n')[0]
        social_support_list.append(social_support)
        
        healthy_life_exp = cells[5].text.split('\n')[0]
        healthy_life_exp_list.append(healthy_life_exp)
        
        freedom = cells[6].text.split('\n')[0]
        freedom_list.append(freedom)
        
        generosity = cells[7].text.split('\n')[0]
        generosity_list.append(generosity)
        
        corruption = cells[8].text.split('\n')[0]
        corruption_list.append(corruption)

In [6]:
df = pd.DataFrame()
df['countries'] = countries
df['happiness'] = happiness_list
df['GDP_per_capita'] = GDP_per_capita_list
df['social_support'] = social_support_list
df['healthy_life_exp'] = healthy_life_exp_list
df['freedom'] = freedom_list
df['generosity'] = generosity_list
df['corruption'] = corruption_list

In [7]:
df.head()

,countries,happiness,GDP_per_capita,social_support,healthy_life_exp,freedom,generosity,corruption
0,Finland,7.769,1.340,1.587,0.986,0.596,0.153,0.393
1,Denmark,7.600,1.383,1.573,0.996,0.592,0.252,0.410
2,Norway,7.554,1.488,1.582,1.028,0.603,0.271,0.341
3,Iceland,7.494,1.380,1.624,1.026,0.591,0.354,0.118
4,Netherlands,7.488,1.396,1.522,0.999,0.557,0.322,0.298

In [8]:
df.tail()

,countries,happiness,GDP_per_capita,social_support,healthy_life_exp,freedom,generosity,corruption
151,Rwanda,3.334,0.359,0.711,0.614,0.555,0.217,0.411
152,Tanzania,3.231,0.476,0.885,0.499,0.417,0.276,0.147
153,Afghanistan,3.203,0.350,0.517,0.361,0.000,0.158,0.025
154,Central African Republic,3.083,0.026,0.000,0.105,0.225,0.235,0.035
155,South Sudan,2.853,0.306,0.575,0.295,0.010,0.202,0.091

In [9]:
df.to_csv('happiness.csv')