# Imports

In [1]:
import pandas as pd
from pandas_datareader import wb

# API exploration

In [117]:
wb.get_indicators().head()

,id,name,unit,source,sourceNote,sourceOrganization,topics
0,1.0.HCount.1.90usd,Poverty Headcount ($1.90 a day),,LAC Equity Lab,The poverty headcount index measures the propo...,b'LAC Equity Lab tabulations of SEDLAC (CEDLAS...,Poverty
1,1.0.HCount.2.5usd,Poverty Headcount ($2.50 a day),,LAC Equity Lab,The poverty headcount index measures the propo...,b'LAC Equity Lab tabulations of SEDLAC (CEDLAS...,Poverty
2,1.0.HCount.Mid10to50,Middle Class ($10-50 a day) Headcount,,LAC Equity Lab,The poverty headcount index measures the propo...,b'LAC Equity Lab tabulations of SEDLAC (CEDLAS...,Poverty
3,1.0.HCount.Ofcl,Official Moderate Poverty Rate-National,,LAC Equity Lab,The poverty headcount index measures the propo...,b'LAC Equity Lab tabulations of data from Nati...,Poverty
4,1.0.HCount.Poor4uds,Poverty Headcount ($4 a day),,LAC Equity Lab,The poverty headcount index measures the propo...,b'LAC Equity Lab tabulations of SEDLAC (CEDLAS...,Poverty

In [118]:
wb.get_countries().head()

,iso3c,iso2c,name,region,adminregion,incomeLevel,lendingType,capitalCity,longitude,latitude
0,ABW,AW,Aruba,Latin America & Caribbean,,High income,Not classified,Oranjestad,-70.0167,12.51670
1,AFG,AF,Afghanistan,South Asia,South Asia,Low income,IDA,Kabul,69.1761,34.52280
2,AFR,A9,Africa,Aggregates,,Aggregates,Aggregates,,NaN,NaN
3,AGO,AO,Angola,Sub-Saharan Africa,Sub-Saharan Africa (excluding high income),Lower middle income,IBRD,Luanda,13.2420,-8.81155
4,ALB,AL,Albania,Europe & Central Asia,Europe & Central Asia (excluding high income),Upper middle income,IBRD,Tirane,19.8172,41.33170

## Internet access

In [140]:
internet = wb.search('access to internet')
internet

,id,name,unit,source,sourceNote,sourceOrganization,topics
14459,gwp2_n,Access to internet (% age 15+),,G20 Financial Inclusion Indicators,,b'',
14460,gwp2_n_1,"Access to internet, female (% age 15+)",,G20 Financial Inclusion Indicators,,b'',
14461,gwp2_n_2,"Access to internet, male (% age 15+)",,G20 Financial Inclusion Indicators,,b'',
14462,gwp2_n_3,"Access to internet, income, poorest 40% (% age...",,G20 Financial Inclusion Indicators,,b'',
14463,gwp2_n_4,"Access to internet, income, richest 60% (% age...",,G20 Financial Inclusion Indicators,,b'',
14464,gwp2_n_5,Access to internet (% ages 15-34),,G20 Financial Inclusion Indicators,,b'',
14465,gwp2_n_6,Access to internet (% ages 35-59),,G20 Financial Inclusion Indicators,,b'',
14466,gwp2_n_7,Access to internet (% age 60+),,G20 Financial Inclusion Indicators,,b'',

In [141]:
df = wb.download(indicator=['gwp2_n','gwp2_n_1','gwp2_n_2','gwp2_n_3','gwp2_n_4','gwp2_n_5','gwp2_n_6','gwp2_n_7','gwp2_n'],country='all',start=2017,end=2017)
df.columns = [title for title in internet['name']]
df = df.dropna()
df

,,Access to internet (% age 15+),"Access to internet, female (% age 15+)","Access to internet, male (% age 15+)","Access to internet, income, poorest 40% (% age 15+)","Access to internet, income, richest 60% (% age 15+)",Access to internet (% ages 15-34),Access to internet (% ages 35-59),Access to internet (% age 60+)
country,year,,,,,,,,
Afghanistan,2017,14.80909,4.882765,24.62060,9.009466,18.66901,18.33455,9.081439,7.316440
Albania,2017,47.62765,44.803910,50.62286,34.689220,56.23954,75.53036,37.041380,17.318520
Algeria,2017,56.46716,52.998200,59.92853,42.665030,65.64495,69.20241,44.924090,27.347940
Argentina,2017,68.76507,70.114890,67.28787,67.570930,69.55928,85.01320,70.846400,29.291000
Armenia,2017,75.05693,73.461630,76.91758,67.423250,80.14458,80.84227,80.506540,52.141280
...,...,...,...,...,...,...,...,...,...
"Venezuela, RB",2017,55.67877,53.415280,58.17471,45.808450,62.22993,70.55145,53.712930,17.863610
Vietnam,2017,51.52416,47.340360,56.07744,37.067750,61.16149,76.11625,37.852840,8.524342
West Bank and Gaza,2017,55.03128,53.860550,56.24088,30.812310,71.13063,60.99529,50.841650,29.335640
Zambia,2017,25.41447,20.395380,30.64323,12.752460,33.85024,30.59592,18.029440,8.907472
Zimbabwe,2017,32.38422,23.320360,42.25463,14.543730,44.25152,38.67941,27.082170,4.095412

In [142]:
df.to_csv('Access_to_internet.csv')

In [165]:
wb.search('export')[:50]

,id,name,unit,source,sourceNote,sourceOrganization,topics
193,5.04.01.02.impexp,Import and export price indexes,,Statistical Capacity Indicators,Import and export price indexes measure change...,b'IMF: International Financial Statistics (IFS...,
925,A1,001.Number of Exporters,,Exporter Dynamics Database – Indicators at Cou...,Exporter-level information on export transacti...,b'',
926,A10i,026.Export Value per Incumbent: Mean,,Exporter Dynamics Database – Indicators at Cou...,Exporter-level information on export transacti...,b'',
927,A10ii,027.Export Value per Incumbent: Median,,Exporter Dynamics Database – Indicators at Cou...,Exporter-level information on export transacti...,b'',
928,A10iii,028.Export Value per Incumbent: StDev.,,Exporter Dynamics Database – Indicators at Cou...,Exporter-level information on export transacti...,b'',
929,A10iv,029.Export Value per Incumbent: First Quartile,,Exporter Dynamics Database – Indicators at Cou...,Exporter-level information on export transacti...,b'',
930,A10v,030.Export Value per Incumbent: Third Quartile,,Exporter Dynamics Database – Indicators at Cou...,Exporter-level information on export transacti...,b'',
945,A6i,006.Export Value per Exporter: Mean,,Exporter Dynamics Database – Indicators at Cou...,Exporter-level information on export transacti...,b'',
946,A6ii,007.Export Value per Exporter: Median,,Exporter Dynamics Database – Indicators at Cou...,Exporter-level information on export transacti...,b'',
947,A6iii,008.Export Value per Exporter: StDev.,,Exporter Dynamics Database – Indicators at Cou...,Exporter-level information on export transacti...,b'',
948,A6iv,009.Export Value per Exporter: First Quartile,,Exporter Dynamics Database – Indicators at Cou...,Exporter-level information on export transacti...,b'',
949,A6v,010.Export Value per Exporter: Third Quartile,,Exporter Dynamics Database – Indicators at Cou...,Exporter-level information on export transacti...,b'',
950,A7i,011.Export Value per Entrant: Mean,,Exporter Dynamics Database – Indicators at Cou...,Exporter-level information on export transacti...,b'',
951,A7ii,012.Export Value per Entrant: Median,,Exporter Dynamics Database – Indicators at Cou...,Exporter-level information on export transacti...,b'',
952,A7iii,013.Export Value per Entrant: StDev.,,Exporter Dynamics Database – Indicators at Cou...,Exporter-level information on export transacti...,b'',
953,A7iv,014.Export Value per Entrant: First Quartile,,Exporter Dynamics Database – Indicators at Cou...,Exporter-level information on export transacti...,b'',
954,A7v,015.Export Value per Entrant: Third Quartile,,Exporter Dynamics Database – Indicators at Cou...,Exporter-level information on export transacti...,b'',
955,A8i,016.Export Value per Exiter: Mean,,Exporter Dynamics Database – Indicators at Cou...,Exporter-level information on export transacti...,b'',
956,A8ii,017.Export Value per Exiter: Median,,Exporter Dynamics Database – Indicators at Cou...,Exporter-level information on export transacti...,b'',
957,A8iii,018.Export Value per Exiter: StDev.,,Exporter Dynamics Database – Indicators at Cou...,Exporter-level information on export transacti...,b'',
958,A8iv,019.Export Value per Exiter: First Quartile,,Exporter Dynamics Database – Indicators at Cou...,Exporter-level information on export transacti...,b'',
959,A8v,020.Export Value per Exiter: Third Quartile,,Exporter Dynamics Database – Indicators at Cou...,Exporter-level information on export transacti...,b'',
960,A9i,021.Export Value per Surviving Entrant: Mean,,Exporter Dynamics Database – Indicators at Cou...,Exporter-level information on export transacti...,b'',
961,A9ii,022.Export Value per Surviving Entrant: Median,,Exporter Dynamics Database – Indicators at Cou...,Exporter-level information on export transacti...,b'',
962,A9iii,023.Export Value per Surviving Entrant: StDev.,,Exporter Dynamics Database – Indicators at Cou...,Exporter-level information on export transacti...,b'',
963,A9iv,024.Export Value per Surviving Entrant: First ...,,Exporter Dynamics Database – Indicators at Cou...,Exporter-level information on export transacti...,b'',
964,A9v,025.Export Value per Surviving Entrant: Third ...,,Exporter Dynamics Database – Indicators at Cou...,Exporter-level information on export transacti...,b'',
1072,B2i,042.Share of top 1% Exporters in TEV (Total Ex...,,Exporter Dynamics Database – Indicators at Cou...,Exporter-level information on export transacti...,b'',
1073,B2ii,043.Share of top 5% Exporters in TEV (Total Ex...,,Exporter Dynamics Database – Indicators at Cou...,Exporter-level information on export transacti...,b'',
1074,B2iii,044.Share of top 25% Exporters in TEV (Total E...,,Exporter Dynamics Database – Indicators at Cou...,Exporter-level information on export transacti...,b'',
1075,B3i,045.Number of HS6 Products per Exporter: Mean,,Exporter Dynamics Database – Indicators at Cou...,Exporter-level information on export transacti...,b'',
1076,B3ii,046.Number of HS6 Products per Exporter: Median,,Exporter Dynamics Database – Indicators at Cou...,Exporter-level information on export transacti...,b'',
1077,B3iii,047.Number of HS6 Products per Exporter: StDev.,,Exporter Dynamics Database – Indicators at Cou...,Exporter-level information on export transacti...,b'',
1078,B4i,048.Number of Destinations per Exporter: Mean,,Exporter Dynamics Database – Indicators at Cou...,Exporter-level information on export transacti...,b'',
1079,B4ii,049.Number of Destinations per Exporter: Median,,Exporter Dynamics Database – Indicators at Cou...,Exporter-level information on export transacti...,b'',
1080,B4iii,050.Number of Destinations per Exporter: StDev.,,Exporter Dynamics Database – Indicators at Cou...,Exporter-level information on export transacti...,b'',
1081,B5i,051.Number of Exporters per HS6 Product: Mean,,Exporter Dynamics Database – Indicators at Cou...,Exporter-level information on export transacti...,b'',
1082,B5ii,052.Number of Exporters per HS6 Product: Median,,Exporter Dynamics Database – Indicators at Cou...,Exporter-level information on export transacti...,b'',
1083,B5iii,053.Number of Exporters per HS6 Product: StDev.,,Exporter Dynamics Database – Indicators at Cou...,Exporter-level information on export transacti...,b'',
1084,B6i,054.Number of Exporters per Destination: Mean,,Exporter Dynamics Database – Indicators at Cou...,Exporter-level information on export transacti...,b'',
1085,B6ii,055.Number of Exporters per Destination: Median,,Exporter Dynamics Database – Indicators at Cou...,Exporter-level information on export transacti...,b'',
1086,B6iii,056.Number of Exporters per Destination: StDev.,,Exporter Dynamics Database – Indicators at Cou...,Exporter-level information on export transacti...,b'',
1539,BM.AG.AGR.TRAC.CD,"Agricultural tractors, exports (FAO, current US$)",,Africa Development Indicators,Agricultural machinery refers to the number of...,"b'Food and Agriculture Organization, electroni...",
1540,BM.AG.AGR.TRAC.NO,"Agricultural tractors, exports",,Africa Development Indicators,Agricultural machinery refers to the number of...,"b'Food and Agriculture Organization, electroni...",
1541,BM.AG.CREL.CD,"Cereal exports (FAO, current US$)",,Africa Development Indicators,"Cereals include wheat, rice, maize, barley, oa...","b'Food and Agriculture Organization, electroni...",
1542,BM.AG.CREL.MT,"Cereal exports quantity (FAO, tonnes)",,Africa Development Indicators,"Cereals include wheat, rice, maize, barley, oa...","b'Food and Agriculture Organization, electroni...",
1640,BX.AG.FRST.CD,"Forest products exports (FAO, current US$)",,Africa Development Indicators,Forest products exports. Data are in current ...,"b'Food and Agriculture Organization, electroni...",
1641,BX.AG.HZ.PEST.CD,"Hazardous pesticides exports (FAO, current US$)",,Africa Development Indicators,"Pesticides refer to insecticides, fungicides, ...","b'Food and Agriculture Organization, electroni...",
1642,BX.AG.PEST.CD,"Pesticides exports (FAO, current US$)",,Africa Development Indicators,Pesticides trade refers to the value of all ty...,"b'Food and Agriculture Organization, electroni...",
1643,BX.FOD.AGRI.CD,"Food exports excluding fish (FAO, current US$)",,Africa Development Indicators,Food exports an are expressed in current U.S. ...,"b'Food and Agriculture Organization, electroni...",

In [155]:
df = wb.download(indicator=['SH.STA.TRAF.P5'],country='all',start=1990,end=2019)
df = df.dropna()
df

                                     SH.STA.TRAF.P5
country                        year
Arab World                     2016       19.446819
                               2013       20.281305
Caribbean small states         2016       15.498151
                               2013       13.767610
Central Europe and the Baltics 2016        8.856706
...                                             ...
Vietnam                        2013       24.500000
Yemen, Rep.                    2013       21.500000
Zambia                         2013       24.700000
Zimbabwe                       2016       34.700000
                               2013       28.200000

[454 rows x 1 columns]